version: '3.1'
services:
  app:
    container_name: springboot
    image: 'docker-spring-boot-postgres:latest'
    build: ./
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresqldb:5432/spaceflight
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=spaceflight